// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'model.dart';

// **************************************************************************
// SqfEntityGenerator
// **************************************************************************

//  These classes was generated by SqfEntity
//  Copyright (c) 2019, All rights reserved. Use of this source code is governed by a
//  Apache license that can be found in the LICENSE file.

//  To use these SqfEntity classes do following:
//  - import model.dart into where to use
//  - start typing ex:Storage.select()... (add a few filters with fluent methods)...(add orderBy/orderBydesc if you want)...
//  - and then just put end of filters / or end of only select()  toSingle() / or toList()
//  - you can select one or return List<yourObject> by your filters and orders
//  - also you can batch update or batch delete by using delete/update methods instead of tosingle/tolist methods
//    Enjoy.. Huseyin Tokpunar

// ignore_for_file:
// BEGIN TABLES
// Storage TABLE
class TableStorage extends SqfEntityTableBase {
  TableStorage() {
    // declare properties of EntityTable
    tableName = 'storage';
    primaryKeyName = 'id';
    primaryKeyType = PrimaryKeyType.integer_unique;
    useSoftDeleting = true;
    // when useSoftDeleting is true, creates a field named 'isDeleted' on the table, and set to '1' this field when item deleted (does not hard delete)

    // declare fields
    fields = [
      SqfEntityFieldBase('path', DbType.text, isNotNull: false),
    ];
    super.init();
  }
  static SqfEntityTableBase _instance;
  static SqfEntityTableBase get getInstance {
    return _instance = _instance ?? TableStorage();
  }
}
// END TABLES

// BEGIN SEQUENCES
// END SEQUENCES

// BEGIN DATABASE MODEL
class MyDbModel extends SqfEntityModelProvider {
  MyDbModel() {
    databaseName = notesDbModel.databaseName;
    password = notesDbModel.password;
    dbVersion = notesDbModel.dbVersion;
    databaseTables = [
      TableStorage.getInstance,
    ];

    bundledDatabasePath = notesDbModel
        .bundledDatabasePath; //'assets/sample.db'; // This value is optional. When bundledDatabasePath is empty then EntityBase creats a new database when initializing the database
  }
  Map<String, dynamic> getControllers() {
    final controllers = <String, dynamic>{};

    return controllers;
  }
}
// END DATABASE MODEL

// BEGIN ENTITIES
// region Storage
class Storage {
  Storage({this.id, this.path, this.isDeleted}) {
    _setDefaultValues();
  }
  Storage.withFields(this.id, this.path, this.isDeleted) {
    _setDefaultValues();
  }
  Storage.withId(this.id, this.path, this.isDeleted) {
    _setDefaultValues();
  }
  Storage.fromMap(Map<String, dynamic> o, {bool setDefaultValues = true}) {
    if (setDefaultValues) {
      _setDefaultValues();
    }
    id = int.tryParse(o['id'].toString());
    if (o['path'] != null) {
      path = o['path'] as String;
    }
    isDeleted = o['isDeleted'] != null
        ? o['isDeleted'] == 1 || o['isDeleted'] == true
        : null;

    isSaved = true;
  }
  // FIELDS (Storage)
  int id;
  String path;
  bool isDeleted;
  bool isSaved;
  BoolResult saveResult;
  // end FIELDS (Storage)

  static const bool _softDeleteActivated = true;
  StorageManager __mnStorage;

  StorageManager get _mnStorage {
    return __mnStorage = __mnStorage ?? StorageManager();
  }

  // METHODS
  Map<String, dynamic> toMap(
      {bool forQuery = false, bool forJson = false, bool forView = false}) {
    final map = <String, dynamic>{};
    if (id != null) {
      map['id'] = id;
    }
    if (path != null) {
      map['path'] = path;
    }

    if (isDeleted != null) {
      map['isDeleted'] = forQuery ? (isDeleted ? 1 : 0) : isDeleted;
    }

    return map;
  }

  Future<Map<String, dynamic>> toMapWithChildren(
      [bool forQuery = false,
      bool forJson = false,
      bool forView = false]) async {
    final map = <String, dynamic>{};
    if (id != null) {
      map['id'] = id;
    }
    if (path != null) {
      map['path'] = path;
    }

    if (isDeleted != null) {
      map['isDeleted'] = forQuery ? (isDeleted ? 1 : 0) : isDeleted;
    }

    return map;
  }

  /// This method returns Json String [Storage]
  String toJson() {
    return json.encode(toMap(forJson: true));
  }

  /// This method returns Json String [Storage]
  Future<String> toJsonWithChilds() async {
    return json.encode(await toMapWithChildren(false, true));
  }

  List<dynamic> toArgs() {
    return [id, path, isDeleted];
  }

  List<dynamic> toArgsWithIds() {
    return [id, path, isDeleted];
  }

  static Future<List<Storage>> fromWebUrl(String url,
      {Map<String, String> headers}) async {
    try {
      final response = await http.get(url, headers: headers);
      return await fromJson(response.body);
    } catch (e) {
      print(
          'SQFENTITY ERROR Storage.fromWebUrl: ErrorMessage: ${e.toString()}');
      return null;
    }
  }

  Future<http.Response> postUrl(String url, {Map<String, String> headers}) {
    return http.post(url, headers: headers, body: toJson());
  }

  static Future<List<Storage>> fromJson(String jsonBody) async {
    final Iterable list = await json.decode(jsonBody) as Iterable;
    var objList = <Storage>[];
    try {
      objList = list
          .map((storage) => Storage.fromMap(storage as Map<String, dynamic>))
          .toList();
    } catch (e) {
      print('SQFENTITY ERROR Storage.fromJson: ErrorMessage: ${e.toString()}');
    }
    return objList;
  }

  static Future<List<Storage>> fromMapList(List<dynamic> data,
      {bool preload = false,
      List<String> preloadFields,
      bool loadParents = false,
      List<String> loadedFields,
      bool setDefaultValues = true}) async {
    final List<Storage> objList = <Storage>[];
    loadedFields = loadedFields ?? [];
    for (final map in data) {
      final obj = Storage.fromMap(map as Map<String, dynamic>,
          setDefaultValues: setDefaultValues);

      objList.add(obj);
    }
    return objList;
  }

  /// returns Storage by ID if exist, otherwise returns null
  ///
  /// Primary Keys: int id
  ///
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  ///
  /// ex: getById(preload:true) -> Loads all related objects
  ///
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  ///
  /// ex: getById(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  ///
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  ///
  /// <returns>returns Storage if exist, otherwise returns null
  Future<Storage> getById(int id,
      {bool preload = false,
      List<String> preloadFields,
      bool loadParents = false,
      List<String> loadedFields}) async {
    if (id == null) {
      return null;
    }
    Storage obj;
    final data = await _mnStorage.getById([id]);
    if (data.length != 0) {
      obj = Storage.fromMap(data[0] as Map<String, dynamic>);
    } else {
      obj = null;
    }
    return obj;
  }

  /// Saves the (Storage) object. If the id field is null, saves as a new record and returns new id, if id is not null then updates record

  /// <returns>Returns id
  Future<int> save() async {
    if (id == null || id == 0 || !isSaved) {
      await _mnStorage.insert(this);
      if (saveResult != null && saveResult.success) {
        isSaved = true;
      }
    } else {
      // id= await _upsert(); // removed in sqfentity_gen 1.3.0+6
      await _mnStorage.update(this);
    }

    return id;
  }

  /// saveAll method saves the sent List<Storage> as a bulk in one transaction
  ///
  /// Returns a <List<BoolResult>>
  static Future<List<dynamic>> saveAll(List<Storage> storages) async {
    // final results = _mnStorage.saveAll('INSERT OR REPLACE INTO storage (id,path,isDeleted)  VALUES (?,?,?)',storages);
    // return results; removed in sqfentity_gen 1.3.0+6
    await MyDbModel().batchStart();
    for (final obj in storages) {
      await obj.save();
    }
    //    return MyDbModel().batchCommit();
    final result = await MyDbModel().batchCommit();

    return result;
  }

  /// Updates if the record exists, otherwise adds a new row

  /// <returns>Returns id
  Future<int> upsert() async {
    try {
      if (await _mnStorage.rawInsert(
              'INSERT OR REPLACE INTO storage (id,path,isDeleted)  VALUES (?,?,?)',
              [id, path, isDeleted]) ==
          1) {
        saveResult = BoolResult(
            success: true,
            successMessage: 'Storage id=$id updated successfully');
      } else {
        saveResult = BoolResult(
            success: false, errorMessage: 'Storage id=$id did not update');
      }
      return id;
    } catch (e) {
      saveResult = BoolResult(
          success: false,
          errorMessage: 'Storage Save failed. Error: ${e.toString()}');
      return 0;
    }
  }

  /// inserts or replaces the sent List<<Storage>> as a bulk in one transaction.
  ///
  /// upsertAll() method is faster then saveAll() method. upsertAll() should be used when you are sure that the primary key is greater than zero
  ///
  /// Returns a BoolCommitResult
  Future<BoolCommitResult> upsertAll(List<Storage> storages) async {
    final results = await _mnStorage.rawInsertAll(
        'INSERT OR REPLACE INTO storage (id,path,isDeleted)  VALUES (?,?,?)',
        storages);
    return results;
  }

  /// Deletes Storage

  /// <returns>BoolResult res.success=Deleted, not res.success=Can not deleted
  Future<BoolResult> delete([bool hardDelete = false]) async {
    print('SQFENTITIY: delete Storage invoked (id=$id)');
    if (!_softDeleteActivated || hardDelete || isDeleted) {
      return _mnStorage
          .delete(QueryParams(whereString: 'id=?', whereArguments: [id]));
    } else {
      return _mnStorage.updateBatch(
          QueryParams(whereString: 'id=?', whereArguments: [id]),
          {'isDeleted': 1});
    }
  }

  /// Recover Storage>

  /// <returns>BoolResult res.success=Recovered, not res.success=Can not recovered
  Future<BoolResult> recover([bool recoverChilds = true]) async {
    print('SQFENTITIY: recover Storage invoked (id=$id)');
    {
      return _mnStorage.updateBatch(
          QueryParams(whereString: 'id=?', whereArguments: [id]),
          {'isDeleted': 0});
    }
  }

  StorageFilterBuilder select(
      {List<String> columnsToSelect, bool getIsDeleted}) {
    return StorageFilterBuilder(this)
      .._getIsDeleted = getIsDeleted == true
      ..qparams.selectColumns = columnsToSelect;
  }

  StorageFilterBuilder distinct(
      {List<String> columnsToSelect, bool getIsDeleted}) {
    return StorageFilterBuilder(this)
      .._getIsDeleted = getIsDeleted == true
      ..qparams.selectColumns = columnsToSelect
      ..qparams.distinct = true;
  }

  void _setDefaultValues() {
    isSaved = false;
    isDeleted = isDeleted ?? false;
  }
  // END METHODS
  // CUSTOM CODES
  /*
      you must define customCode property of your SqfEntityTable constant for ex:
      const tablePerson = SqfEntityTable(
      tableName: 'person',
      primaryKeyName: 'id',
      primaryKeyType: PrimaryKeyType.integer_auto_incremental,
      fields: [
        SqfEntityField('firstName', DbType.text),
        SqfEntityField('lastName', DbType.text),
      ],
      customCode: '''
       String fullName()
       { 
         return '$firstName $lastName';
       }
      ''');
     */
  // END CUSTOM CODES
}
// endregion storage

// region StorageField
class StorageField extends SearchCriteria {
  StorageField(this.storageFB) {
    param = DbParameter();
  }
  DbParameter param;
  String _waitingNot = '';
  StorageFilterBuilder storageFB;

  StorageField get not {
    _waitingNot = ' NOT ';
    return this;
  }

  StorageFilterBuilder equals(dynamic pValue) {
    param.expression = '=';
    storageFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, storageFB.parameters, param, SqlSyntax.EQuals,
            storageFB._addedBlocks)
        : setCriteria(pValue, storageFB.parameters, param, SqlSyntax.NotEQuals,
            storageFB._addedBlocks);
    _waitingNot = '';
    storageFB._addedBlocks.needEndBlock[storageFB._blockIndex] =
        storageFB._addedBlocks.retVal;
    return storageFB;
  }

  StorageFilterBuilder equalsOrNull(dynamic pValue) {
    param.expression = '=';
    storageFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, storageFB.parameters, param,
            SqlSyntax.EQualsOrNull, storageFB._addedBlocks)
        : setCriteria(pValue, storageFB.parameters, param,
            SqlSyntax.NotEQualsOrNull, storageFB._addedBlocks);
    _waitingNot = '';
    storageFB._addedBlocks.needEndBlock[storageFB._blockIndex] =
        storageFB._addedBlocks.retVal;
    return storageFB;
  }

  StorageFilterBuilder isNull() {
    storageFB._addedBlocks = setCriteria(
        0,
        storageFB.parameters,
        param,
        SqlSyntax.IsNULL.replaceAll(SqlSyntax.notKeyword, _waitingNot),
        storageFB._addedBlocks);
    _waitingNot = '';
    storageFB._addedBlocks.needEndBlock[storageFB._blockIndex] =
        storageFB._addedBlocks.retVal;
    return storageFB;
  }

  StorageFilterBuilder contains(dynamic pValue) {
    if (pValue != null) {
      storageFB._addedBlocks = setCriteria(
          '%${pValue.toString()}%',
          storageFB.parameters,
          param,
          SqlSyntax.Contains.replaceAll(SqlSyntax.notKeyword, _waitingNot),
          storageFB._addedBlocks);
      _waitingNot = '';
      storageFB._addedBlocks.needEndBlock[storageFB._blockIndex] =
          storageFB._addedBlocks.retVal;
    }
    return storageFB;
  }

  StorageFilterBuilder startsWith(dynamic pValue) {
    if (pValue != null) {
      storageFB._addedBlocks = setCriteria(
          '${pValue.toString()}%',
          storageFB.parameters,
          param,
          SqlSyntax.Contains.replaceAll(SqlSyntax.notKeyword, _waitingNot),
          storageFB._addedBlocks);
      _waitingNot = '';
      storageFB._addedBlocks.needEndBlock[storageFB._blockIndex] =
          storageFB._addedBlocks.retVal;
      storageFB._addedBlocks.needEndBlock[storageFB._blockIndex] =
          storageFB._addedBlocks.retVal;
    }
    return storageFB;
  }

  StorageFilterBuilder endsWith(dynamic pValue) {
    if (pValue != null) {
      storageFB._addedBlocks = setCriteria(
          '%${pValue.toString()}',
          storageFB.parameters,
          param,
          SqlSyntax.Contains.replaceAll(SqlSyntax.notKeyword, _waitingNot),
          storageFB._addedBlocks);
      _waitingNot = '';
      storageFB._addedBlocks.needEndBlock[storageFB._blockIndex] =
          storageFB._addedBlocks.retVal;
    }
    return storageFB;
  }

  StorageFilterBuilder between(dynamic pFirst, dynamic pLast) {
    if (pFirst != null && pLast != null) {
      storageFB._addedBlocks = setCriteria(
          pFirst,
          storageFB.parameters,
          param,
          SqlSyntax.Between.replaceAll(SqlSyntax.notKeyword, _waitingNot),
          storageFB._addedBlocks,
          pLast);
    } else if (pFirst != null) {
      if (_waitingNot != '') {
        storageFB._addedBlocks = setCriteria(pFirst, storageFB.parameters,
            param, SqlSyntax.LessThan, storageFB._addedBlocks);
      } else {
        storageFB._addedBlocks = setCriteria(pFirst, storageFB.parameters,
            param, SqlSyntax.GreaterThanOrEquals, storageFB._addedBlocks);
      }
    } else if (pLast != null) {
      if (_waitingNot != '') {
        storageFB._addedBlocks = setCriteria(pLast, storageFB.parameters, param,
            SqlSyntax.GreaterThan, storageFB._addedBlocks);
      } else {
        storageFB._addedBlocks = setCriteria(pLast, storageFB.parameters, param,
            SqlSyntax.LessThanOrEquals, storageFB._addedBlocks);
      }
    }
    _waitingNot = '';
    storageFB._addedBlocks.needEndBlock[storageFB._blockIndex] =
        storageFB._addedBlocks.retVal;
    return storageFB;
  }

  StorageFilterBuilder greaterThan(dynamic pValue) {
    param.expression = '>';
    storageFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, storageFB.parameters, param,
            SqlSyntax.GreaterThan, storageFB._addedBlocks)
        : setCriteria(pValue, storageFB.parameters, param,
            SqlSyntax.LessThanOrEquals, storageFB._addedBlocks);
    _waitingNot = '';
    storageFB._addedBlocks.needEndBlock[storageFB._blockIndex] =
        storageFB._addedBlocks.retVal;
    return storageFB;
  }

  StorageFilterBuilder lessThan(dynamic pValue) {
    param.expression = '<';
    storageFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, storageFB.parameters, param, SqlSyntax.LessThan,
            storageFB._addedBlocks)
        : setCriteria(pValue, storageFB.parameters, param,
            SqlSyntax.GreaterThanOrEquals, storageFB._addedBlocks);
    _waitingNot = '';
    storageFB._addedBlocks.needEndBlock[storageFB._blockIndex] =
        storageFB._addedBlocks.retVal;
    return storageFB;
  }

  StorageFilterBuilder greaterThanOrEquals(dynamic pValue) {
    param.expression = '>=';
    storageFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, storageFB.parameters, param,
            SqlSyntax.GreaterThanOrEquals, storageFB._addedBlocks)
        : setCriteria(pValue, storageFB.parameters, param, SqlSyntax.LessThan,
            storageFB._addedBlocks);
    _waitingNot = '';
    storageFB._addedBlocks.needEndBlock[storageFB._blockIndex] =
        storageFB._addedBlocks.retVal;
    return storageFB;
  }

  StorageFilterBuilder lessThanOrEquals(dynamic pValue) {
    param.expression = '<=';
    storageFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, storageFB.parameters, param,
            SqlSyntax.LessThanOrEquals, storageFB._addedBlocks)
        : setCriteria(pValue, storageFB.parameters, param,
            SqlSyntax.GreaterThan, storageFB._addedBlocks);
    _waitingNot = '';
    storageFB._addedBlocks.needEndBlock[storageFB._blockIndex] =
        storageFB._addedBlocks.retVal;
    return storageFB;
  }

  StorageFilterBuilder inValues(dynamic pValue) {
    storageFB._addedBlocks = setCriteria(
        pValue,
        storageFB.parameters,
        param,
        SqlSyntax.IN.replaceAll(SqlSyntax.notKeyword, _waitingNot),
        storageFB._addedBlocks);
    _waitingNot = '';
    storageFB._addedBlocks.needEndBlock[storageFB._blockIndex] =
        storageFB._addedBlocks.retVal;
    return storageFB;
  }
}
// endregion StorageField

// region StorageFilterBuilder
class StorageFilterBuilder extends SearchCriteria {
  StorageFilterBuilder(Storage obj) {
    whereString = '';
    qparams = QueryParams();
    parameters = <DbParameter>[];
    orderByList = <String>[];
    groupByList = <String>[];
    _addedBlocks = AddedBlocks(<bool>[], <bool>[]);
    _addedBlocks.needEndBlock.add(false);
    _addedBlocks.waitingStartBlock.add(false);
    _pagesize = 0;
    _page = 0;
    _obj = obj;
  }
  AddedBlocks _addedBlocks;
  int _blockIndex = 0;
  List<DbParameter> parameters;
  List<String> orderByList;
  Storage _obj;
  QueryParams qparams;
  int _pagesize;
  int _page;

  /// put the sql keyword 'AND'
  StorageFilterBuilder get and {
    if (parameters.isNotEmpty) {
      parameters[parameters.length - 1].wOperator = ' AND ';
    }
    return this;
  }

  /// put the sql keyword 'OR'
  StorageFilterBuilder get or {
    if (parameters.isNotEmpty) {
      parameters[parameters.length - 1].wOperator = ' OR ';
    }
    return this;
  }

  /// open parentheses
  StorageFilterBuilder get startBlock {
    _addedBlocks.waitingStartBlock.add(true);
    _addedBlocks.needEndBlock.add(false);
    _blockIndex++;
    if (_blockIndex > 1) {
      _addedBlocks.needEndBlock[_blockIndex - 1] = true;
    }
    return this;
  }

  /// String whereCriteria, write raw query without 'where' keyword. Like this: 'field1 like 'test%' and field2 = 3'
  StorageFilterBuilder where(String whereCriteria, {dynamic parameterValue}) {
    if (whereCriteria != null && whereCriteria != '') {
      final DbParameter param = DbParameter(
          columnName: parameterValue == null ? null : '',
          hasParameter: parameterValue != null);
      _addedBlocks = setCriteria(parameterValue ?? 0, parameters, param,
          '($whereCriteria)', _addedBlocks);
      _addedBlocks.needEndBlock[_blockIndex] = _addedBlocks.retVal;
    }
    return this;
  }

  /// page = page number,
  ///
  /// pagesize = row(s) per page
  StorageFilterBuilder page(int page, int pagesize) {
    if (page > 0) {
      _page = page;
    }
    if (pagesize > 0) {
      _pagesize = pagesize;
    }
    return this;
  }

  /// int count = LIMIT
  StorageFilterBuilder top(int count) {
    if (count > 0) {
      _pagesize = count;
    }
    return this;
  }

  /// close parentheses
  StorageFilterBuilder get endBlock {
    if (_addedBlocks.needEndBlock[_blockIndex]) {
      parameters[parameters.length - 1].whereString += ' ) ';
    }
    _addedBlocks.needEndBlock.removeAt(_blockIndex);
    _addedBlocks.waitingStartBlock.removeAt(_blockIndex);
    _blockIndex--;
    return this;
  }

  /// argFields might be String or List<String>.
  ///
  /// Example 1: argFields='name, date'
  ///
  /// Example 2: argFields = ['name', 'date']
  StorageFilterBuilder orderBy(dynamic argFields) {
    if (argFields != null) {
      if (argFields is String) {
        orderByList.add(argFields);
      } else {
        for (String s in argFields as List<String>) {
          if (s != null && s.isNotEmpty) {
            orderByList.add(' $s ');
          }
        }
      }
    }
    return this;
  }

  /// argFields might be String or List<String>.
  ///
  /// Example 1: argFields='field1, field2'
  ///
  /// Example 2: argFields = ['field1', 'field2']
  StorageFilterBuilder orderByDesc(dynamic argFields) {
    if (argFields != null) {
      if (argFields is String) {
        orderByList.add('$argFields desc ');
      } else {
        for (String s in argFields as List<String>) {
          if (s != null && s.isNotEmpty) {
            orderByList.add(' $s desc ');
          }
        }
      }
    }
    return this;
  }

  /// argFields might be String or List<String>.
  ///
  /// Example 1: argFields='field1, field2'
  ///
  /// Example 2: argFields = ['field1', 'field2']
  StorageFilterBuilder groupBy(dynamic argFields) {
    if (argFields != null) {
      if (argFields is String) {
        groupByList.add(' $argFields ');
      } else {
        for (String s in argFields as List<String>) {
          if (s != null && s.isNotEmpty) {
            groupByList.add(' $s ');
          }
        }
      }
    }
    return this;
  }

  /// argFields might be String or List<String>.
  ///
  /// Example 1: argFields='name, date'
  ///
  /// Example 2: argFields = ['name', 'date']
  StorageFilterBuilder having(dynamic argFields) {
    if (argFields != null) {
      if (argFields is String) {
        havingList.add(argFields);
      } else {
        for (String s in argFields as List<String>) {
          if (s != null && s.isNotEmpty) {
            havingList.add(' $s ');
          }
        }
      }
    }
    return this;
  }

  StorageField setField(StorageField field, String colName, DbType dbtype) {
    return StorageField(this)
      ..param = DbParameter(
          dbType: dbtype,
          columnName: colName,
          wStartBlock: _addedBlocks.waitingStartBlock[_blockIndex]);
  }

  StorageField _id;
  StorageField get id {
    return _id = setField(_id, 'id', DbType.integer);
  }

  StorageField _path;
  StorageField get path {
    return _path = setField(_path, 'path', DbType.text);
  }

  StorageField _isDeleted;
  StorageField get isDeleted {
    return _isDeleted = setField(_isDeleted, 'isDeleted', DbType.bool);
  }

  bool _getIsDeleted;

  void _buildParameters() {
    if (_page > 0 && _pagesize > 0) {
      qparams
        ..limit = _pagesize
        ..offset = (_page - 1) * _pagesize;
    } else {
      qparams
        ..limit = _pagesize
        ..offset = _page;
    }
    for (DbParameter param in parameters) {
      if (param.columnName != null) {
        if (param.value is List && !param.hasParameter) {
          param.value = param.dbType == DbType.text
              ? '\'${param.value.join('\',\'')}\''
              : param.value.join(',');
          whereString += param.whereString
              .replaceAll('{field}', param.columnName)
              .replaceAll('?', param.value.toString());
          param.value = null;
        } else {
          if (param.value is Map<String, dynamic> &&
              param.value['sql'] != null) {
            param
              ..whereString = param.whereString
                  .replaceAll('?', param.value['sql'].toString())
              ..dbType = DbType.integer
              ..value = param.value['args'];
          }
          whereString +=
              param.whereString.replaceAll('{field}', param.columnName);
        }
        if (!param.whereString.contains('?')) {
        } else {
          switch (param.dbType) {
            case DbType.bool:
              param.value =
                  param.value == null ? null : param.value == true ? 1 : 0;
              param.value2 =
                  param.value2 == null ? null : param.value2 == true ? 1 : 0;
              break;
            case DbType.date:
            case DbType.datetime:
            case DbType.datetimeUtc:
              param.value = param.value == null
                  ? null
                  : (param.value as DateTime).millisecondsSinceEpoch;
              param.value2 = param.value2 == null
                  ? null
                  : (param.value2 as DateTime).millisecondsSinceEpoch;
              break;
            default:
          }
          if (param.value != null) {
            if (param.value is List) {
              for (var p in param.value) {
                whereArguments.add(p);
              }
            } else {
              whereArguments.add(param.value);
            }
          }
          if (param.value2 != null) {
            whereArguments.add(param.value2);
          }
        }
      } else {
        whereString += param.whereString;
      }
    }
    if (Storage._softDeleteActivated) {
      if (whereString != '') {
        whereString =
            '${!_getIsDeleted ? 'ifnull(isDeleted,0)=0 AND' : ''} ($whereString)';
      } else if (!_getIsDeleted) {
        whereString = 'ifnull(isDeleted,0)=0';
      }
    }

    if (whereString != '') {
      qparams.whereString = whereString;
    }
    qparams
      ..whereArguments = whereArguments
      ..groupBy = groupByList.join(',')
      ..orderBy = orderByList.join(',')
      ..having = havingList.join(',');
  }

  /// Deletes List<Storage> bulk by query
  ///
  /// <returns>BoolResult res.success=Deleted, not res.success=Can not deleted
  Future<BoolResult> delete([bool hardDelete = false]) async {
    _buildParameters();
    var r = BoolResult();

    if (Storage._softDeleteActivated && !hardDelete) {
      r = await _obj._mnStorage.updateBatch(qparams, {'isDeleted': 1});
    } else {
      r = await _obj._mnStorage.delete(qparams);
    }
    return r;
  }

  /// Recover List<Storage> bulk by query
  Future<BoolResult> recover() async {
    _getIsDeleted = true;
    _buildParameters();
    print('SQFENTITIY: recover Storage bulk invoked');
    return _obj._mnStorage.updateBatch(qparams, {'isDeleted': 0});
  }

  /// using:
  ///
  /// update({'fieldName': Value})
  ///
  /// fieldName must be String. Value is dynamic, it can be any of the (int, bool, String.. )
  Future<BoolResult> update(Map<String, dynamic> values) {
    _buildParameters();
    if (qparams.limit > 0 || qparams.offset > 0) {
      qparams.whereString =
          'id IN (SELECT id from storage ${qparams.whereString.isNotEmpty ? 'WHERE ${qparams.whereString}' : ''}${qparams.limit > 0 ? ' LIMIT ${qparams.limit}' : ''}${qparams.offset > 0 ? ' OFFSET ${qparams.offset}' : ''})';
    }
    return _obj._mnStorage.updateBatch(qparams, values);
  }

  /// This method always returns Storage Obj if exist, otherwise returns null
  ///
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  ///
  /// ex: toSingle(preload:true) -> Loads all related objects
  ///
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  ///
  /// ex: toSingle(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  ///
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  ///
  /// <returns>List<Storage>
  Future<Storage> toSingle(
      {bool preload = false,
      List<String> preloadFields,
      bool loadParents = false,
      List<String> loadedFields}) async {
    _pagesize = 1;
    _buildParameters();
    final objFuture = _obj._mnStorage.toList(qparams);
    final data = await objFuture;
    Storage obj;
    if (data.isNotEmpty) {
      obj = Storage.fromMap(data[0] as Map<String, dynamic>);
    } else {
      obj = null;
    }
    return obj;
  }

  /// This method returns int. [Storage]
  ///
  /// <returns>int
  Future<int> toCount([VoidCallback Function(int c) storageCount]) async {
    _buildParameters();
    qparams.selectColumns = ['COUNT(1) AS CNT'];
    final storagesFuture = await _obj._mnStorage.toList(qparams);
    final int count = storagesFuture[0]['CNT'] as int;
    if (storageCount != null) {
      storageCount(count);
    }
    return count;
  }

  /// This method returns List<Storage> [Storage]
  ///
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  ///
  /// ex: toList(preload:true) -> Loads all related objects
  ///
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  ///
  /// ex: toList(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  ///
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  ///
  /// <returns>List<Storage>
  Future<List<Storage>> toList(
      {bool preload = false,
      List<String> preloadFields,
      bool loadParents = false,
      List<String> loadedFields}) async {
    final data = await toMapList();
    final List<Storage> storagesData = await Storage.fromMapList(data,
        preload: preload,
        preloadFields: preloadFields,
        loadParents: loadParents,
        loadedFields: loadedFields,
        setDefaultValues: qparams.selectColumns == null);
    return storagesData;
  }

  /// This method returns Json String [Storage]
  Future<String> toJson() async {
    final list = <dynamic>[];
    final data = await toList();
    for (var o in data) {
      list.add(o.toMap(forJson: true));
    }
    return json.encode(list);
  }

  /// This method returns Json String. [Storage]
  Future<String> toJsonWithChilds() async {
    final list = <dynamic>[];
    final data = await toList();
    for (var o in data) {
      list.add(await o.toMapWithChildren(false, true));
    }
    return json.encode(list);
  }

  /// This method returns List<dynamic>. [Storage]
  ///
  /// <returns>List<dynamic>
  Future<List<dynamic>> toMapList() async {
    _buildParameters();
    return await _obj._mnStorage.toList(qparams);
  }

  /// This method returns Primary Key List SQL and Parameters retVal = Map<String,dynamic>. [Storage]
  ///
  /// retVal['sql'] = SQL statement string, retVal['args'] = whereArguments List<dynamic>;
  ///
  /// <returns>List<String>
  Map<String, dynamic> toListPrimaryKeySQL([bool buildParameters = true]) {
    final Map<String, dynamic> _retVal = <String, dynamic>{};
    if (buildParameters) {
      _buildParameters();
    }
    _retVal['sql'] = 'SELECT `id` FROM storage WHERE ${qparams.whereString}';
    _retVal['args'] = qparams.whereArguments;
    return _retVal;
  }

  /// This method returns Primary Key List<int>.
  /// <returns>List<int>
  Future<List<int>> toListPrimaryKey([bool buildParameters = true]) async {
    if (buildParameters) {
      _buildParameters();
    }
    final List<int> idData = <int>[];
    qparams.selectColumns = ['id'];
    final idFuture = await _obj._mnStorage.toList(qparams);

    final int count = idFuture.length;
    for (int i = 0; i < count; i++) {
      idData.add(idFuture[i]['id'] as int);
    }
    return idData;
  }

  /// Returns List<dynamic> for selected columns. Use this method for 'groupBy' with min,max,avg..  [Storage]
  ///
  /// Sample usage: (see EXAMPLE 4.2 at https://github.com/hhtokpinar/sqfEntity#group-by)
  Future<List<dynamic>> toListObject() async {
    _buildParameters();

    final objectFuture = _obj._mnStorage.toList(qparams);

    final List<dynamic> objectsData = <dynamic>[];
    final data = await objectFuture;
    final int count = data.length;
    for (int i = 0; i < count; i++) {
      objectsData.add(data[i]);
    }
    return objectsData;
  }

  /// Returns List<String> for selected first column
  ///
  /// Sample usage: await Storage.select(columnsToSelect: ['columnName']).toListString()
  Future<List<String>> toListString(
      [VoidCallback Function(List<String> o) listString]) async {
    _buildParameters();

    final objectFuture = _obj._mnStorage.toList(qparams);

    final List<String> objectsData = <String>[];
    final data = await objectFuture;
    final int count = data.length;
    for (int i = 0; i < count; i++) {
      objectsData.add(data[i][qparams.selectColumns[0]].toString());
    }
    if (listString != null) {
      listString(objectsData);
    }
    return objectsData;
  }
}
// endregion StorageFilterBuilder

// region StorageFields
class StorageFields {
  static TableField _fId;
  static TableField get id {
    return _fId = _fId ?? SqlSyntax.setField(_fId, 'id', DbType.integer);
  }

  static TableField _fPath;
  static TableField get path {
    return _fPath = _fPath ?? SqlSyntax.setField(_fPath, 'path', DbType.text);
  }

  static TableField _fIsDeleted;
  static TableField get isDeleted {
    return _fIsDeleted = _fIsDeleted ??
        SqlSyntax.setField(_fIsDeleted, 'isDeleted', DbType.integer);
  }
}
// endregion StorageFields

//region StorageManager
class StorageManager extends SqfEntityProvider {
  StorageManager()
      : super(MyDbModel(),
            tableName: _tableName,
            primaryKeyList: _primaryKeyList,
            whereStr: _whereStr);
  static final String _tableName = 'storage';
  static final List<String> _primaryKeyList = ['id'];
  static final String _whereStr = 'id=?';
}

//endregion StorageManager
class MyDbModelSequenceManager extends SqfEntityProvider {
  MyDbModelSequenceManager() : super(MyDbModel());
}
// END OF ENTITIES
